title = "cancelInput"
category = "keyboard"
isScreen = true
summary = "Cancels all previous input commands."
description = ""
example = """
$.screen( "300x200" );
$.print( "\\n" );
$.input( "What is your name? ", null );
$.onkey( "Escape", "down", function () {
	$.print( "\\nInput Canceled" );
	$.cancelInput();
}, true );"""
parameters = [ ]

[[returns]]
type = "void"
description = "This function does not return a value."
