title = "cancelInput"
category = "keyboard"
isScreen = true
summary = "Cancels all previous input commands."
description = ""
example = """
$.screen("300x200");\r
$.print("\\n");\r
$.input("What is your name?", null);\r
$.onkey( "Escape", "down", function () {  \r
\t$.print("\\nInput Canceled");\r
\t$.cancelInput();\r
}, true );"""

[[parameters]]
name = "name"
type = "any"
description = "The name provided to the input command."
optional = true

[[returns]]
type = "void"
description = "This function does not return a value."
