title = "clearKeys"
category = "keyboard"
isScreen = false
summary = "Clears event handlers for keyboard events."
description = ""
example = """
$.screen("300x200");\r
$.print("\\n");\r
$.onkey( "any", "down", function (key) {\r
\t$.print(key.key + " pressed.");\r
});\r
$.onkey( "Escape", "down", function (key) {\r
\t$.print(key.key + " pressed.");\r
\t$.clearKeys();\r
});"""

parameters = [ ]
[[returns]]
type = "void"
description = "This function does not return a value."
