title = "clearEvents"
category = "core"
isScreen = false
summary = "Clears event handlers for mouse and touch events on the screen."
example = """
$.screen( "300x200" );
$.print( "Move mouse or touch to paint screen click/touch up to stop." );
$.onpress( "move", pressMove );
$.onpress( "up", pressStop );

// Press move function
function pressMove( data ) {
	$.setPosPx( data.x, data.y );
	var pos = $.getPos();
	$.setPos( pos.col, pos.row );
	$.setColor( 8 );
	$.print( "+", true );
}

// Press stop function
function pressStop() {
	$.setColor( 14 );
	var pos = $.getPos();
	$.setPos( pos.col - 4, pos.row );
	$.print( "Stopped!", true );
	$.clearEvents();
}
"""

parameters = [ ]
[[returns]]
type = "void"
description = "This function does not return a value."
