title = "createAudioPool"
category = "sound"
isScreen = false
summary = """
Creates a group of audio players that can play sounds. Audio pools are useful if you want to\r
\tplay a sound multiple times without reloading it each time. The number of audio players you\r
\tspecify determines how many sounds you can play simultanously. If you only want to play one\r
\tsound at a time set 1 for the poolSize."""
description = ""
example = """
$.screen( "300x200" );
var bombPool = $.createAudioPool( "media/bomb.wav", 5 );
$.ready( function () {
	$.print( "Press any key to play bomb sound." );
	$.onkey( "any", "down", () => {
		$.print( "BOOM ", true );
		$.playAudioPool( bombPool );
	} );
} );
"""

[[parameters]]
name = "src"
type = "string"
description = "The source of the audio file."

[[parameters]]
name = "poolSize"
type = "number"
description = "The number of audio players."
optional = true

[[returns]]
type = "void"
description = "This function does not return a value."
