title = "deleteAudioPool"
category = "sound"
isScreen = false
summary = "Deletes an audio pool."
description = ""
example = """
$.screen( "300x200" );
var bombPool = $.createAudioPool( "media/bomb.wav", 5 );
$.ready( function () {
	$.print( "Press any key to try to play bomb sound." );
	$.deleteAudioPool( bombPool );
	$.onkey( "any", "down", () => {
		$.print( "SILENCE ", true );
		$.playAudioPool( bombPool );
	} );
} );
"""

[[parameters]]
name = "audioId"
type = "string"
description = "The id of the audio pool."

[[returns]]
type = "void"
description = "This function does not return a value."
