title = "deleteAudioPool"
category = "sound"
isScreen = false
summary = "Deletes an audio pool."
description = ""
example = """
var bombPool = $.createAudioPool("/sounds/bomb.wav", 1);\r
$.deleteAudioPool(bombPool);"""

[[parameters]]
name = "audioId"
type = "string"
description = "The id of the audio pool."

[[returns]]
type = "void"
description = "This function does not return a value."
