title = "drawImage"
category = "images"
isScreen = true
summary = "Draws an image on to the screen.  Note: this method will fail if it gets called before the image is loaded."
description = ""
example = """
$.screen( "300x200" );\r
var monkey = $.loadImage( "/images/monkey.png" );\r
$.ready( function () {\r
\t$.drawImage( monkey, 150, 100, 0, 0.5, 0.5 );\r
} );\r
"""

[[parameters]]
name = "name"
type = "any"
description = "Name or id of the image."

[[parameters]]
name = "x"
type = "any"
description = "Horizontal coordinate."

[[parameters]]
name = "y"
type = "any"
description = "Vertical coordinate."

[[parameters]]
name = "angle"
type = "any"
description = "Rotate the image in degrees."
optional = true

[[parameters]]
name = "anchorX"
type = "any"
description = "Horizontal rotation coordinate."
optional = true

[[parameters]]
name = "anchorY"
type = "any"
description = "Vertical rotation coordinate."
optional = true

[[parameters]]
name = "alpha"
type = "any"
description = "Transparency amount number 0-100."
optional = true

[[parameters]]
name = "scaleX"
type = "any"
description = "Horizontal scaling amount."
optional = true

[[parameters]]
name = "scaleY"
type = "any"
description = "Vertical scaling amount."
optional = true

[[returns]]
type = "void"
description = "This function does not return a value."
