title = "filterImg"
category = "graphics"
isScreen = true
summary = "Filters a screens colors."
description = ""
example = """
$.screen( "300x200" );
$.circle( 150, 100, 50, "red" );
$.filterImg( function ( color, x, y ) {
	color.r = color.r - Math.round( Math.tan( ( x + y ) / 10 ) * 128 );
	color.g = color.g + Math.round( Math.cos( x / 7 ) * 128 );
	color.b = color.b + Math.round( Math.sin( y / 5 ) * 128 );
	return color;
} );
"""

[[parameters]]
name = "filter"
type = "function"
signature = "( color: PiColor, x: number, y: number ) => PiColor"
description = "Callback (color, x, y) to be called on each pixel."

[[returns]]
type = "void"
description = "This function does not return a value."
