title = "filterImg"
category = "graphics"
isScreen = true
summary = "Filters a screens colors."
description = ""
example = """
$.screen("300x200");\r
$.circle(150, 100, 50, "red");\r
$.filterImg(function (color, x, y) {\r
\tcolor.r = color.r - Math.round( Math.tan( ( x + y ) / 10 ) * 128 );\r
\tcolor.g = color.g + Math.round( Math.cos( x / 7 ) * 128 );\r
\tcolor.b = color.b + Math.round( Math.sin( y / 5 ) * 128 );\r
\treturn color;\r
});"""

[[parameters]]
name = "filter"
type = "function"
description = "Callback (color, x, y) to be called on each pixel."

[[returns]]
type = "void"
description = "This function does not return a value."
