title = "get"
category = "primitives"
isScreen = true
summary = """
Gets an area of pixels from the screen and returns an array of color indices.\r
It's counterpart, the put method, copies the contents of the array back onto\r
the screen."""
description = ""
example = """
$.screen( "300x200" );\r
$.circle( 150, 110, 50, 4 );\r
var colors = $.get( 105, 85, 110, 90 );\r
$.print( "[" );\r
for( var i = 0; i < colors.length; i++ ) {\r
\t$.print( "    [ " + colors[ i ].join( ", " ) + " ]," );\r
}\r
$.print( "]" );\r
$.put( colors, 20, 80 );\r
"""

[[parameters]]
name = "x1"
type = "number"
description = "First horizontal coordiante."

[[parameters]]
name = "y1"
type = "number"
description = "First vertical coordinate."

[[parameters]]
name = "x2"
type = "number"
description = "Second horizontal coordiante."

[[parameters]]
name = "y2"
type = "number"
description = "Second vertical coordinate."

[[parameters]]
name = "tolerance"
type = "number"
description = "If the color is not in the color palette then attempt to find the closest fit color."
optional = true

[[returns]]
type = "Array<Array<number>>"
description = "A 2-dimensional array of color indices."
