title = "getCols"
category = "print"
isScreen = true
summary = "Gets the max number of printable characters in a row on the screen."
description = ""
parameters = [ ]
example = """
// Print a line of *'s on the top of the screen\r
$.screen( "300x200" );\r
var cols = $.getCols();\r
var msg = "";\r
for( var i = 0; i < cols; i++ ) {\r
\tmsg += "*";\r
}\r
$.print( msg );\r
"""

[[returns]]
type = "void"
description = "An integer containing the max number of printable characters for a row on the screen."
