title = "getImage"
category = "images"
isScreen = true
summary = """
Gets an area of pixels from the screen and draws it an in-memory image that can be used with the\r
drawImage function."""
description = ""
example = """
$.screen( "300x200" );\r
$.circle( 150, 110, 50, 4 );\r
var circle = $.getImage( null, 100, 40, 200, 160 );\r
$.drawImage( circle, 20, 80 );\r
"""

[[parameters]]
name = "name"
type = "any"
description = ". The name of the image for reference."
optional = true

[[parameters]]
name = "x1"
type = "any"
description = "First horizontal coordiante."

[[parameters]]
name = "y1"
type = "any"
description = "First vertical coordinate."

[[parameters]]
name = "x2"
type = "any"
description = "Second horizontal coordiante."

[[parameters]]
name = "y2"
type = "any"
description = "Second vertical coordinate."

[[returns]]
type = "void"
description = "The name or id of the image."
