title = "getImage"
category = "images"
isScreen = true
summary = """
Gets an image from an area on the current screen.
"""
description = """
Gets an area of pixels from the screen and draws it to an in-memory image that can be used with the
drawImage function.

Note: This function has been renamed in version 2.0 to createImageFromScreen. The 2.0 getImage
function returns an imageObject that has been loaded with loadImage.
"""
example = """
$.screen( "300x200" );
$.circle( 150, 110, 50, 4 );
var circle = $.getImage( null, 100, 40, 200, 160 );
$.drawImage( circle, 20, 80 );
"""

[[parameters]]
name = "name"
type = "string"
description = "The name of the image for reference."
optional = true

[[parameters]]
name = "x1"
type = "number"
description = "First horizontal coordiante."

[[parameters]]
name = "y1"
type = "number"
description = "First vertical coordinate."

[[parameters]]
name = "x2"
type = "number"
description = "Second horizontal coordiante."

[[parameters]]
name = "y2"
type = "number"
description = "Second vertical coordinate."

[[returns]]
type = "string"
description = "The name or id of the image."
