title = "getPal"
category = "colors"
isScreen = true
summary = "Returns the current color palette as an array."
description = "Gets the current color palette from the screen and returns an array with all the color data."
example = """
$.screen("300x200");\r
var pal = $.getPal();\r
$.setColor( 2 );\r
$.print( pal[ 2 ].s );\r
"""

parameters = [ ]
[[returns]]
type = "Array<number>"
typeDesc = "*Array"
description = "An array of color data for the current screen's color palette."
