title = "getPixel"
category = "color"
isScreen = true
summary = "Gets the pixel color from the screen and returns the color data."
description = ""
example = """
$.screen( "300x200" );\r
$.setColor( 5 );\r
$.pset( 55, 55 );\r
var pixel = $.getPixel( 55, 55 );\r
$.print( pixel.s );\r
"""

[[parameters]]
name = "x"
type = "number"
description = "The horizontal coordinate for the pixel"

[[parameters]]
name = "y"
type = "number"
description = "The vertical coordinate for the pixel"

[[returns]]
type = "PiColor"
description = "The color data { r: red, g: green, b: blue, a: alpha: s: rgbaString, s2: hexString }."
