title = "getPal"
category = "color"
isScreen = true
summary = "Gets the current color palette from the screen and returns an array with all the color data."
description = ""
parameters = [ ]
example = """
$.screen("300x200");\r
var pal = $.getPal();\r
$.setColor( 2 );\r
$.print( pal[ 2 ].s );\r
"""

[[returns]]
type = "void"
description = "An array of color data for the current screen's color palette."
