title = "getRows"
category = "print"
isScreen = true
summary = "Gets the max number of printable characters in a column on the screen."
description = ""
parameters = [ ]
example = """
// Print a line of *'s on the left of the screen\r
$.screen("300x200");\r
var rows = $.getRows();\r
var msg = "";\r
for(var i = 0; i < rows; i++) {\r
\tmsg += "*\\n";\r
}\r
$.print(msg);\r
"""

[[returns]]
type = "void"
description = "An integer containing the number of rows of printable characters on a screen."
