title = "getScreen"
category = "core"
isScreen = false
summary = "Gets a screen API object by screen ID."
description = """
Retrieves the screen API object for a specific screen ID. This allows you to call all the graphics
operations for a specific screen. This means you do not have to call setScreen to set the active
screen every time you want to draw on a different screen. There is also a tiny performance advantage
for drawing commands called directly on a screen object.
"""

[[parameters]]
name = "screenId"
type = "number"
description = "The screen ID to retrieve."

[[returns]]
type = "object"
description = "Screen API object with all graphics commands and screen=true and id property."

example = """
$.screen( "320x200" );
$.screen( "320x200" );
const screen0 = $.getScreen( 0 );
const screen1 = $.getScreen( 1 );
screen0.print( `Screen: ${screen0.id}` );
screen1.print( `Screen: ${screen1.id}` );
$.print( "Active Screen" );
"""
