title = "getScreen"
category = "graphics"
isScreen = false
summary = "Gets the screen based on a screen id."
description = ""
example = """
$.screen( "300x200" );\r
var $screen = $.getScreen( 0 );\r
$screen.print( "This is screen 0." );\r
"""

[[parameters]]
name = "screenId"
type = "any"
description = "An integer that identifies a screen that was previously created using the screen command."

[[returns]]
type = "void"
description = "A screen object that contains a reference to all the methods that can be called on a screen."
