title = "height"
category = "graphics"
isScreen = true
summary = "Returns the height of the screen."
description = ""
parameters = [ ]
example = """
$.screen( "300x200" );\r
$.print( "Height: " + $.height() );\r
"""

[[returns]]
type = "void"
description = "A number containing the height of the screen."
