title = "ingamepads"
category = "gamepad"
isScreen = false
summary = "Gets the most recent gamepad status."
description = ""
example = """
$.screen( "300x200" );
$.setColor( 15 );
let x = 150;
let y = 100;
let lt = 0;
requestAnimationFrame( run );
function run( t ) {
	let factor = ( t - lt ) * 0.5;
	lt = t;
	let pads = $.ingamepads();
	$.cls();
	if( pads.length > 0 ) {
		x = $.util.clamp( x + pads[ 0 ].axes2[ 0 ] * factor, 0, 299 );
		y = $.util.clamp( y + pads[ 0 ].axes2[ 1 ] * factor, 0, 199 );
		$.circle( Math.floor( x ), Math.floor( y ) , 10 );
		$.pset( Math.floor( x ), Math.floor( y ) );
	}
	requestAnimationFrame( run );
}
"""

parameters = [ ]
[[returns]]
type = "void"
description = "An array of gamepad objects."
