title = "inkey"
category = "keyboard"
isScreen = false
summary = "Gets the most recent status of keys."
description = ""
example = """
$.screen( "300x200" );\r
var frame = requestAnimationFrame( run );\r
function run() {\r
\tvar keys, key;\r
\tkeys = $.inkey();\r
\t$.cls();\r
\t$.print( "Press any key" );\r
\tfor( key in $.inkey() ) {\r
\t\t$.print( "--------------------------" );\r
\t\t$.print( "key:      " + keys[ key ].key );\r
\t\t$.print( "location: " + keys[ key ].location );\r
\t\t$.print( "code:     " + keys[ key ].code );\r
\t\t$.print( "keyCode:  " + keys[ key ].keyCode );\r
\t}\r
\tframe = requestAnimationFrame( run );\r
}\r
"""

[[parameters]]
name = "key"
type = "any"
description = "Name (string) or keyCode (integer) of key to return the status. Leave blank for the status of all keys that have been pressed."
optional = true

[[returns]]
type = "void"
description = """
If the first parameter is left blank then it will return an array of key data objects. If not then it returns the\r
an object containing data for a single key."""
