title = "inmouse"
category = "mouse"
isScreen = true
summary = "Gets the most recent mouse status."
description = ""
parameters = [ ]
example = """
$.screen( "4x4" );\r
var interval = setInterval( function () {\r
\tvar mouse = $.inmouse();\r
\tif( mouse.buttons > 0 ) {\r
\t\t$.setColor( Math.floor( Math.random() * 9 ) + 1 );\r
\t\t$.pset( mouse.x, mouse.y );\r
\t}\r
}, 50 );\r
"""

[[returns]]
type = "void"
description = "An object containing data about the mouse's position and button status."
