title = "inpress"
category = "mouse,touch"
isScreen = true
summary = "Gets the most recent mouse or touch status."
description = ""
example = """
$.screen( "4x4" );\r
$.startTouch();\r
$.setPinchZoom( false );\r
var interval = setInterval( function () {\r
\tvar press = $.inpress();\r
\tif( press.buttons > 0 ) {\r
\t\t$.setColor( Math.floor( Math.random() * 9 ) + 1 );\r
\t\t$.pset( press.x, press.y );\r
\t}\r
}, 50 );\r
"""

parameters = [ ]
[[returns]]
type = "void"
description = "An object containing data about the mouse or touch position and press status."
