title = "intouch"
category = "touch"
isScreen = true
summary = "Gets the most recent touch status."
description = ""
parameters = [ ]
example = """
$.screen( "4x4" );\r
$.startTouch();\r
$.setPinchZoom( false );\r
var interval = setInterval( function () {\r
\tvar touches = $.intouch();\r
\tif( touches.length > 0 ) {\r
\t\t$.setColor( Math.floor( Math.random() * 9 ) + 1 );\r
\t\t$.pset( touches[ 0 ].x, touches[ 0 ].y );\r
\t}\r
}, 50 );\r
"""

[[returns]]
type = "void"
description = "An array of touch objects."
