title = "loadFont"
category = "print"
isScreen = false
summary = "Loads a font from an image or encoded string."
description = ""
example = """
var font = $.loadFont( \r
  "/images/gnsh-bitmapfont-colour2.png", 5, 12, \r
  " !\\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]" +\r
  "^_`abcdefghijklmnopqrstuvwxyz{|}~"\r
);\r
$.ready( function () {\r
\t$.screen( "300x200" );\r
  $.setBgColor( "#241c1c" );\r
\t$.setFont( font );\r
  $.print();\r
\t$.print( " Hello World!" );\r
\t$.print( " 123456789" );\r
\t$.print( " #$%&?" );\r
} );\r
"""

[[parameters]]
name = "fontSrc"
type = "string|HTMLImageElement|HTMLCanvasElement"
description = "The source location of the image or the encoded string location."

[[parameters]]
name = "width"
type = "number"
description = "The width of each character in the font."

[[parameters]]
name = "height"
type = "number"
description = "The height of each character in the font."

[[parameters]]
name = "charSet"
type = "array|string"
description = "A string or an array of integers containing the ascii value for each font character in order."
optional = true

[[parameters]]
name = "isEncoded"
type = "boolean"
description = "Boolean to load the font from an encoded string."
optional = true

[[returns]]
type = "number"
description = "The id of the font."
