title = "loadFont"
category = "text"
isScreen = false
summary = "Loads a font from an image or encoded string."
description = ""
example = """
var font = $.loadFont(
	"media/gnsh.png", 5, 12,
	" !\\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]" +
	"^_`abcdefghijklmnopqrstuvwxyz{|}~"
);
$.ready( function () {
	$.screen( "300x200" );
	$.setBgColor( "#241c1c" );
	$.setFont( font );
	$.print();
	$.print( " Hello World!" );
	$.print( " 123456789" );
	$.print( " #$%&?" );
} );
"""

[[parameters]]
name = "fontSrc"
type = "string | HTMLImageElement | HTMLCanvasElement"
typeDesc = "*Many"
description = "The source location of the image or the encoded string location."

[[parameters]]
name = "width"
type = "number"
description = "The width of each character in the font."

[[parameters]]
name = "height"
type = "number"
description = "The height of each character in the font."

[[parameters]]
name = "charSet"
type = "Array<number> | string"
typeDesc = "*Many"
description = "A string or an array of integers containing the ascii value for each font character in order."
optional = true

[[parameters]]
name = "isEncoded"
type = "boolean"
description = "Boolean to load the font from an encoded string."
optional = true

[[returns]]
type = "number"
description = "The id of the font."
