title = "paint"
category = "primitives"
isScreen = true
isBlocking = true
summary = "Fills in areas of the screen that are the same color."
description = ""

[[parameters]]
name = "x"
type = "number"
description = "The horizontal coordinate from where to start the paint algorithm."

[[parameters]]
name = "y"
type = "number"
description = "The vertical coordinate from where to start the paint algorithm."

[[parameters]]
name = "fillColor"
type = "any"
description = "The fill color for floodfill operation. Can be a palette index or color value (string, array, object, number)."

[[parameters]]
name = "tolerance"
type = "number"
description = "A number between 0 and 1 that allows you to set how sensitive the algorithm is to color differences."
optional = true

[[returns]]
type = "void"
description = "This function does not return a value."

example = """
var color = [ 255, 255, 255 ];\r
var color2 = [ 25, 85, 125 ];\r
$.screen( "256x256" );\r
$.setColor( 15 );\r
$.setPen( "pixel", 1, 100 );\r
for( i = 0; i < 128; i++ ) {\r
\tcolor[ 0 ] -= 2;\r
\tcolor[ 1 ] -= 2;\r
\tcolor[ 2 ] -= 2;\r
\t$.setColor( color );\r
\t$.rect( i, i, 255 - i * 2 + 1, 255 - i * 2 + 1 );\r
}\r
$.setPen( "pixel", 1 );\r
$.print( "Click screen to paint" );\r
$.onclick( function ( mouse ) {\r
\t$.paint( mouse.x, mouse.y, color2, 0.75 );\r
} );\r
"""
