title = "paint"
category = "primitives"
isScreen = true
isBlocking = true
summary = "Fills in areas of the screen that are the same color."
description = ""
example = """
var color = [ 255, 255, 255 ];
var color2 = [ 25, 85, 125 ];
$.screen( "256x256" );
$.setColor( 15 );
$.setPen( "pixel", 1, 100 );
for( i = 0; i < 128; i++ ) {
	color[ 0 ] -= 2;
	color[ 1 ] -= 2;
	color[ 2 ] -= 2;
	$.setColor( color );
	$.rect( i, i, 255 - i * 2 + 1, 255 - i * 2 + 1 );
}
$.setPen( "pixel", 1 );
$.print( "Click screen to paint" );
$.onclick( function ( mouse ) {
	$.paint( mouse.x, mouse.y, color2, 0.75 );
} );
"""

[[parameters]]
name = "x"
type = "number"
description = "The horizontal coordinate from where to start the paint algorithm."

[[parameters]]
name = "y"
type = "number"
description = "The vertical coordinate from where to start the paint algorithm."

[[parameters]]
name = "fillColor"
type = "any"
description = "The fill color for floodfill operation. Can be a palette index or color value (string, array, object, number)."

[[parameters]]
name = "tolerance"
type = "number"
description = "A number between 0 and 1 that allows you to set how sensitive the algorithm is to color differences."
optional = true

[[returns]]
type = "void"
description = "This function does not return a value."
