title = "playAudioPool"
category = "sound"
isScreen = false
summary = "Plays an audio pool sound."
description = ""
example = """
$.screen( "300x200" );
var bombPool = $.createAudioPool( "media/bomb.wav", 5 );
$.ready( function () {
	$.print( "Press any key to play bomb sound." );
	$.onkey( "any", "down", () => {
		$.print( "BOOM ", true );
		$.playAudioPool( bombPool );
	}, false, true );
} );
"""

[[parameters]]
name = "audioId"
type = "any"
description = "The id of the audio pool to play."

[[parameters]]
name = "volume"
type = "any"
description = "Sets the volume level. Use a float value between 0 and 1."

[[parameters]]
name = "startTime"
type = "any"
description = "Allows you to choose a specific time in seconds at which the audio starts."

[[parameters]]
name = "duration"
type = "any"
description = "Max length in seconds the audio will play."

[[returns]]
type = "void"
description = "This function does not return a value."
