title = "point"
isScreen = true
summary = "Gets the pixel color from the screen and returns the color palette index."
description = ""
example = """
$.screen( "300x200" );\r
$.setColor( 5 );\r
$.pset( 55, 55 );\r
var pixel = $.point( 55, 55 );\r
$.print( pixel );\r
"""

[[parameters]]
name = "x"
type = "any"
description = "The horizontal coordinate for the pixel"

[[parameters]]
name = "y"
type = "any"
description = "The vertical coordinate for the pixel"

[[returns]]
type = "void"
description = "The color index (integer)."
