title = "print"
category = "text"
isScreen = true
summary = """
Prints text onto the screen and moves the text cursor to the next line. Will automatically\r
vertically scroll the text and screen image up when text cursor reaches the bottom of the screen."""
description = ""
example = """
$.screen( "300x200" );\r
$.print( "Welcome to PI JS", false, true );\r
$.print();\r
$.print( "This is a line of text." );\r
$.print( "This is inline text", true );\r
$.print( ". Some more inline text.", true );\r
$.print();\r
$.print( "The End" );\r
"""

[[parameters]]
name = "msg"
type = "string"
description = "The text message to print on the screen."
optional = true

[[parameters]]
name = "inLine"
type = "boolean"
description = "Does not move the text cursor to the next line."
optional = true

[[parameters]]
name = "isCentered"
type = "boolean"
description = "Centers the text horizontally on the screen."
optional = true

[[returns]]
type = "void"
description = "This function does not return a value."
