title = "put"
category = "primitives"
isScreen = true
summary = """
Writes a 2-dimensional array of color values onto the screen. It's counterpart the get statement\r
will create an array of color values that you can use with the put statement. Or you can create\r
your own array to use."""
description = ""
example = """
var data = [\r
\t[  1,  2,  3,  4,  5,  6 ],\r
\t[  7,  8,  9, 10, 11, 12 ],\r
\t[ 13, 14, 15, 16, 17, 18 ]\r
]\r
$.screen( "30x20" );\r
$.put( data, 1, 1 );\r
"""

[[parameters]]
name = "data"
type = "any"
description = "The 2d array of color values."

[[parameters]]
name = "x"
type = "any"
description = "The horizontal coordinate of the starting position to write the pixels."

[[parameters]]
name = "y"
type = "any"
description = "The vertical coordinate of the starting position to write the pixels."

[[parameters]]
name = "includeZero"
type = "any"
description = "If set to true then it will copy 0 (transparent) pixels."

[[returns]]
type = "void"
description = "This function does not return a value."
