title = "removeScreen"
category = "graphics"
isScreen = true
summary = "Removes the active screen from memory and the DOM."
description = ""
parameters = [ ]
example = """
$.screen( "300x200" );\r
$.setColor( 5 );\r
$.rect( 25, 25, 150, 100, 2 );\r
$.removeScreen();\r
"""

[[returns]]
type = "void"
description = "This function does not return a value."
