title = "screen"
category = "graphics"
isScreen = false
summary = """
When the screen command is called it will create a canvas element and when graphics\r
commands are called they will manipulate the canvas created. There are three types\r
of canvas styles that can be created a fullscreen canvas that gets appended to the\r
body of the page, a canvas that gets appended to a container element supplied, or\r
an offscreen canvas.\r
<br /><br />\r
The screen command must be called before any graphics commands can be called.\r
<br /><br />\r
The aspect command allows certain types of screen resolutioins to be used. An x is\r
used to specify specific pixel dimensions of the screen. A : is used to provide a\r
aspect ratio. An e is to extend the canvas to fill 100% of the screen regardless of\r
aspect ratio. \r
<br /><br />\r
Examples:<br />\r
300x200 = A canvas that has data for 300x200 canvas filled to fit in the screen dimensions with a 3:2 pixel ratio. <br />\r
16:9 = A canvas that has data and the maximum screen size for the 16:9 aspect ratio. <br />\r
640e480 = A canvas that tries to fit 640x480 resolution but will extend the data and \r
the canvas size to fill the entire screen. <br />\r
<br />\r
If aspect is left blank then the canvas will fill the screen 100% width and height."""
description = ""
example = """
$.screen( "300e200" );\r
$.line( 0, 0, $.width(), $.height() );\r
$.line( 0, $.height(), $.width(), 0 );\r
"""

[[parameters]]
name = "aspect"
type = "string"
description = "Specify the dimensions of the screen using string in the format of: (width)(x/:/e)(height). Ie: 300x200."
optional = true

[[parameters]]
name = "container"
type = "string|HTMLElement"
description = "A DOM element or a string that contains the id tag of a dom element to use as the container for the canvas."
optional = true

[[parameters]]
name = "isOffscreen"
type = "boolean"
description = "Is the canvas an offscreen buffer. If true canvas will not show on screen but can be used as an offscreen buffer."
optional = true

[[parameters]]
name = "willReadFrequently"
type = "boolean"
description = "This sets the image data to not use hardware acceleration. This will help speed things up if you are using a lot of pixel mode primitive graphics commands. It won't help with drawImage or drawSprite commands."
optional = true

[[parameters]]
name = "noStyles"
type = "boolean"
description = "Create a canvas that has no css applied to it. Just use a default canvas element."
optional = true

[[parameters]]
name = "isMultiple"
type = "boolean"
description = "Set the auto size of the canvas to only expand to exact multiples of the target resolution."
optional = true

[[parameters]]
name = "resizeCallback"
type = "function"
signature = "( fromSize: { width: number; height: number }, toSize: { width: number; height: number } ) => void"
description = "A function that will get called after any time the canvas gets resized."
optional = true

[[returns]]
type = "Screen"
description = "Screen API object with all graphics command."
