title = "setAutoRender"
category = "graphics"
isScreen = true
summary = "Enable automatic rendering after drawing in pixel mode"
description = """
Auto render will automatically render any graphics drawn using pixel mode after any drawing routine
is called using a microtask that executes after the current execution thread. Auto render is set by
default. Use setAutoRender to enable and disable the auto rendering.
"""
example = """
$.screen( "300x200" );
$.line( 1, 1, 299, 199 );
$.setAutoRender( false );
// Note nothing will render because auto render is disabled
"""

[[parameters]]
name = "isAutoRender"
type = "boolean"
description = "If set to true then autorender will run"

[[returns]]
type = "void"
description = "This function does not return a value."
