title = "setAutoRender"
category = "graphics"
isScreen = true
summary = """
Auto render will automatically render any graphics drawn using pixel mode\r
after any drawing routine is called using a microtask that executes after\r
the current execution thread. Auto render is set by default. Use setAutoRender\r
to enable and disable the auto rendering."""
description = ""
example = """
$.screen( "300x200" );\r
$.line( 1, 1, 299, 199 );\r
$.setAutoRender( false );\r
// Note nothing will render because auto render is disabled\r
"""

[[parameters]]
name = "isAutoRender"
type = "any"
description = "If set to true then autorender will run"

[[returns]]
type = "void"
description = "This function does not return a value."
