title = "setActionKey"
category = "keyboard"
isScreen = false
summary = "Disables the default behavior for a key."
description = """
This is helpful if you want to use a key that has default behaviour that the web browser you want
to disable.  Such as if you want to use the function keys in your game/app you would need to call
setActionKey to disable the web browser default behaviour.
"""
example = """
$.screen( "200x200" );
$.setActionKey( 17 );
$.setActionKey( "KeyS" );
setInterval( function () {
	let keys = $.inkey();
	$.cls();
	$.print( "Press Ctrl+S." );
	let key = $.inkey( 17 );
	if( key ) {
		$.print( "Control key is pressed." );
	} else {
		$.print( "Control key is not pressed." );
	}
	for( key in keys ) {
		$.print( "--------------------------" );
		$.print( "key:      " + keys[ key ].key );
		$.print( "location: " + keys[ key ].location );
		$.print( "code:     " + keys[ key ].code );
		$.print( "keyCode:  " + keys[ key ].keyCode );
	}
}, 60 );
"""

[[parameters]]
name = "key"
type = "any"
description = "The key you wish to disable default behaviour."

[[parameters]]
name = "isEnabled"
type = "any"
description = "If set to true or left blank then it disables default behaviour. False re-enables default behaviour."
optional = true

[[returns]]
type = "void"
description = "This function does not return a value."
