title = "setBlendMode"
category = "primitives"
isScreen = true
summary = "Sets the alpha blend mode when drawing."
description = """
Normal will set the pixel to the exact color. Blended will mix the colors if the alpha channel of
the current color is not 100%.
"""
example = """
$.screen( "300x200" );
$.rect( 20, 20, 80, 80, "#AA0000FF" );
$.render();
$.setBlendMode( "blend" );
$.rect( 40, 40, 80, 80, "#00AA0088" );
"""

[[parameters]]
name = "mode"
type = "any"
description = "The mode of blend choices are normal or blend."

[[returns]]
type = "void"
description = "This function does not return a value."
