title = "setColors"
category = "colors"
isScreen = true
summary = "Set multiple colors for multi-color fonts"
description = """
Sets an array of color values for use with multi-color fonts using the print statement. The first 
color in the array will be used in all drawing commands while the rest are only used in multi-color
fonts.
"""
example = """
$.setColors( [ 1, 2, 3, 4 ] );
"""

[[parameters]]
name = "colors"
type = "any"
description = "An array of color values to be set."

[[returns]]
type = "void"
description = "This function does not return a value."
