title = "setContainerBgColor"
category = "color"
isScreen = true
summary = "Sets the background color of the canvas container."
description = ""
example = """
$.screen( "300x200" );\r
$.print( "Hello" );\r
$.setContainerBgColor( 5 );\r
"""

[[parameters]]
name = "color"
type = "any"
description = "The color to set the new background for the canvas container"

[[returns]]
type = "void"
description = "This function does not return a value."
