title = "setChar"
category = "print"
isScreen = true
summary = "Overwrites a character in the current font set."
description = ""
example = """
$.screen( "300x200" );\r
$.setFont( 2 );\r
$.setChar( 97, "1092ba547cc6fe92" );\r
$.setChar( 98, "423c2418187e1818" );\r
$.setChar( 99, "7cd67cfec6aafe00" );\r
$.setChar( 100, "00183c667e5a42c3" );\r
$.setChar( 101, "008199FFDBFFBD18" );\r
\r
$.print( " abcde f" );\r
"""

[[parameters]]
name = "code"
type = "any"
description = "The ascii character code you want to replace."

[[parameters]]
name = "data"
type = "any"
description = "Either a 2d array containing numbers or a hex string that when converted to binary represents the character data."

[[returns]]
type = "void"
description = "This function does not return a value."
