title = "setDefaultPal"
category = "color"
isScreen = false
summary = "Sets the default color palette for new screens."
description = ""
example = """
var colors = [\r
\t"black", "red", "green", "blue", \r
\t"navy", "orange", "purple", "gray",\r
\t"white", "pink", "brown", "cyan"\r
];\r
$.setDefaultPal( colors );\r
$.screen( "300x200" );\r
for( var i = 0; i < colors.length; i++ ) {\r
\t$.setColor( i );\r
\t$.print( i + " = " + colors[ i ] );\r
}\r
"""

[[parameters]]
name = "pal"
type = "any"
description = "An array of color values to use as new palette."

[[returns]]
type = "void"
description = "This function does not return a value."
