title = "setDefaultFont"
category = "font"
isScreen = false
summary = "Sets the default font for a new screen."
description = ""
example = """
$.setDefaultFont( 3 );\r
$.screen( "300x200" );\r
$.print( "Hello World" );\r
"""

[[parameters]]
name = "fontId"
type = "any"
description = "Font id for the new default"

[[returns]]
type = "void"
description = "This function does not return a value."
