title = "setDefaultFont"
category = "text"
isScreen = false
summary = "Sets the default font for new screens."
description = """
Sets the default font ID that will be used when new screens are created. The font must already
be loaded using loadFont.
"""
example = """
const fontId = $.loadFont( {
	"src": "media/gnsh.png",
	"width": 5,
	"height": 12,
	"margin": 0,
	"charset": " !\\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]" +
			   "^_`abcdefghijklmnopqrstuvwxyz{|}~"
} );
$.ready( () => {
	$.setDefaultFont( fontId );
	$.screen( "300x200" );
	$.setBgColor( "#555" );
	$.setPosPx( 0, 85 );
	$.print( "The quick brown fox jumped over the lazy dogs! 123456789", true, true );
} );
"""

[[parameters]]
name = "fontId"
type = "number"
description = "Font ID from loadFont to use as default for new screens."

[[returns]]
type = "void"
description = "This function does not return a value."

