title = "setDefaultPal"
category = "colors"
isScreen = false
summary = "Sets the default color palette for new screens."
description = ""
example = """
var colors = [
	"black", "red", "green", "blue",
	"navy", "orange", "purple", "gray",
	"white", "pink", "brown", "cyan"
];
$.setDefaultPal( colors );
$.screen( "300x200" );
for( var i = 0; i < colors.length; i++ ) {
	$.setColor( i );
	$.print( i + " = " + colors[ i ] );
}
"""

[[parameters]]
name = "pal"
type = "any"
description = "An array of color values to use as new palette."

[[returns]]
type = "void"
description = "This function does not return a value."
