title = "setFont"
category = "print"
isScreen = true
summary = """
Sets a font on a screen. The font must already be loaded with the \r
loadFont command. There are several preloaded fonts that come with\r
Pi.js. Font 0 = 6x6, font 1 = 6x8, font 2 = 8x8, font 3 = 8x14, font\r
4 = 8x16."""
description = ""
example = """
$.screen( "300x200" );\r
for( var i = 0; i < 4; i++ ) {\r
\t$.setFont( i );\r
\t$.print( "Font - " + i );\r
}\r
"""

[[parameters]]
name = "fontId"
type = "any"
description = "The id of the font to set. The default fonts loaded are."

[[returns]]
type = "void"
description = "This function does not return a value."
