title = "setFontSize"
category = "text"
isScreen = true
summary = "Sets the font-size for bitmap fonts. Can only be used in bitmap fonts."
description = ""
example = """
var font = $.loadFont(
	"media/gnsh.png", 5, 12,
	" !\\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]" +
	"^_`abcdefghijklmnopqrstuvwxyz{|}~"
);
$.ready( function () {
	$.screen( "100x100" );
	$.setBgColor( "#333" );
	$.setFont( font );
	$.print( "ABCD" );
	$.setFontSize( 20, 20 );
	$.print( "ABCD" );
} );
"""

[[parameters]]
name = "width"
type = "any"
description = "The width of the font."

[[parameters]]
name = "height"
type = "any"
description = "The height of the font."

[[returns]]
type = "void"
description = "This function does not return a value."
