title = "setFont"
category = "text"
isScreen = true
summary = "Sets the font for the current screen."
description = """
Sets the active font for text rendering on the current screen. The font must already be loaded
using loadFont. Several default fonts are preloaded: 0=6x6, 1=6x8 (default), 2=8x8, 3=8x14, 4=8x16.
"""
example = """
$.screen( "300x200" );
for( var i = 0; i < 4; i++ ) {
	$.setFont( i );
	$.print( "Font - " + i );
}
"""

[[parameters]]
name = "fontId"
type = "number"
description = "The id of the font to set. The default fonts loaded are."

[[returns]]
type = "void"
description = "This function does not return a value."
