title = "setPen"
category = "primatives"
isScreen = true
summary = "Sets the pen to use for drawing operations."
description = ""
example = """
$.screen( "300x200" );\r
$.setPen( "circle", 5, [ 32, 16, 8, 0 ] );\r
$.line( 30, 80, 270, 50 );\r
$.pset( 150, 100 );\r
$.draw( "BR15 D15 R100 D30 L15" );\r
"""

[[parameters]]
name = "pen"
type = "any"
description = "A string that is either circle, square, or pixel for the shape of the pen."

[[parameters]]
name = "size"
type = "any"
description = "A number for the size of the pen."

[[parameters]]
name = "noise"
type = "any"
description = "Noise is either a number between 0 and 128 or an array of 4 values between 0 and 128 that represents the range of color values for red/green/blue/alpha. Noise does not work for anti-alias drawing mode."
optional = true

[[returns]]
type = "void"
description = "This function does not return a value."
