title = "setPalColor"
category = "color"
isScreen = true
summary = "Sets a color value in the current screen's palette."
description = ""
example = """
$.screen( "300x200" );\r
$.setColor( 2 );\r
$.print( "Hello" );\r
$.setPalColor( 2, "purple" );\r
$.print( "Hello" );\r
"""

[[parameters]]
name = "index"
type = "any"
description = "The index value of the color to change."

[[parameters]]
name = "color"
type = "any"
description = "Palette index or color value (string, array, object, number)."

[[returns]]
type = "void"
description = "This function does not return a value."
