title = "setPos"
category = "print"
isScreen = true
summary = "Sets the position of the print cursor using columns and rows based on the font size."
description = ""
example = """
$.screen( "300x200" );\r
$.setPos( 5, 10 );\r
$.print( "X" );\r
$.setPos( 10, 15 );\r
$.print( "Y" );\r
"""

[[parameters]]
name = "col"
type = "any"
description = "The column value where to move the print cursor."

[[parameters]]
name = "row"
type = "any"
description = "The row value where to move the print cursor."

[[returns]]
type = "void"
description = "This function does not return a value."
