title = "setVolume"
category = "sound"
isScreen = false
summary = "Sets the master volume for all sound commands."
description = ""
example = """
$.setVolume( 0.15 );
$.play( "Q1o3L8ED+ED+Eo2Bo3DCL2o2A" );
setTimeout( () => {
	$.setVolume( 1 );
}, 730 );
"""

[[parameters]]
name = "volume"
type = "any"
description = "The volume between 0 and 1 that sets the master volume."

[[returns]]
type = "void"
description = "This function does not return a value."
