title = "startTouch"
category = "touch"
isScreen = true
summary = """
Starts the touch event listeners for the screen. This will get called automatically when any\r
touch command gets called."""
description = ""
parameters = [ ]
example = """
$.screen( "4x4" );\r
$.startTouch();\r
$.setPinchZoom( false );\r
$.ontouch( "start", function ( touches ) {\r
\tvar touch = touches[ 0 ];\r
\t$.setColor( Math.floor( Math.random() * 9 ) + 1 );\r
\t$.pset( touch.x, touch.y );\r
} );\r
"""

[[returns]]
type = "void"
description = "This function does not return a value."
