title = "startKeyboard"
category = "keyboard"
isScreen = false
summary = """
Starts tracking keyboard input. This gets automatically called the \r
first time any keyboard method (inkey, onkey, input) gets called so\r
calling startKeyboard is not necessary unless you explicitly call\r
stopKeyboard."""
description = ""
example = """
$.screen( "300x200" );\r
\r
var hitboxColor = 2;\r
var hitbox = {\r
\t"x": 175,\r
\t"y": 75,\r
\t"width": 100,\r
\t"height": 100\r
};\r
var msg = "";\r
var isGreen = true;\r
\r
$.onclick( clickBox, false, hitbox );\r
$.onkey( "any", "down", function ( key ) {\r
\tmsg = "You pressed " + key.key + ".";\r
\tdrawScreen();\r
} );\r
$.onkey( "any", "up", function ( key ) {\r
\tmsg = "";\r
\tdrawScreen();\r
} );\r
\r
drawScreen();\r
\r
function drawScreen() {\r
\t$.cls();\r
\t$.setColor( 7 );\r
\t$.print( "Press any key" );\r
\t$.print( "Click the box to toggle keyboard." );\r
\t$.print( msg );\r
\t$.setColor( hitboxColor );\r
\t$.rect( hitbox );\r
}\r
\r
function clickBox() {\r
\tisGreen = !isGreen;\r
\tif( isGreen ) {\r
\t\thitboxColor = 2;\r
\t\t$.startKeyboard();\r
\t} else {\r
\t\t$.stopKeyboard();\r
\t\thitboxColor = 4;\r
\t}\r
\tdrawScreen();\r
}\r
"""

parameters = [ ]
[[returns]]
type = "void"
description = "This function does not return a value."
