title = "stopSound"
category = "sound"
isScreen = false
summary = "Stops sounds made from the sound command. Leave soundId blank to stop all sounds."
description = ""
example = """
var duration = 0.05;\r
var volume = 0.5;\r
var decay = 0.03;\r
var totalDuration = 0;\r
var i;\r
for( i = 0; i < 30; i++ ) {\r
\t$.sound(\r
\t\t240 + i * 8, duration, volume, "sawtooth", totalDuration, 0,\r
\t\tdecay\r
\t);\r
\ttotalDuration += duration + decay;\r
}\r
\r
var timeout = setTimeout( function () {\r
\t$.stopSound();\r
}, 750 );\r
"""

[[parameters]]
name = "soundId"
type = "any"
description = "The soundId to be stopped."

[[returns]]
type = "void"
description = "This function does not return a value."
