title = "stopAudioPool"
category = "sound"
isScreen = false
summary = "Stops and audio pool if it is currently playing audio."
description = ""
example = """
var bombPool = $.createAudioPool( "/sounds/bomb.wav", 1 );\r
var timeout = 0;\r
$.ready( function () {\r
\t$.playAudioPool( bombPool );\r
\ttimeout = setTimeout( function () {\r
\t\t$.stopAudioPool( bombPool );\r
\t}, 500 );\r
} );\r
"""

[[parameters]]
name = "audioId"
type = "any"
description = "The audio id of the audio pool."

[[returns]]
type = "void"
description = "This function does not return a value."
