title = "stopMouse"
category = "mouse"
isScreen = true
summary = "Stops tracking mouse input."
description = ""
example = """
var isMouseEnabled = true;\r
$.screen( "300x200" );\r
$.onkey( "m", "down", function () {\r
\tisMouseEnabled = !isMouseEnabled;\r
\tif( isMouseEnabled ) {\r
\t\t$.startMouse();\r
\t} else {\r
\t\t$.stopMouse();\r
\t}\r
\tdrawScreen();\r
} );\r
$.onmouse( "move", function ( data ) {\r
\t$.setPosPx( data.x, data.y );\r
\tvar pos = $.getPos();\r
\t$.setPos( pos.col, pos.row );\r
\t$.setColor( pos.col );\r
\t$.print( "+", true );\r
} );\r
\r
drawScreen();\r
\r
function drawScreen() {\r
\t$.cls();\r
\t$.setColor( 7 );\r
\t$.print();\r
\t$.print( " Press 'm' key to toggle mouse" );\r
\t$.print( isMouseEnabled ? " Mouse Enabled" : " Mouse Disabled" );\r
\t$.setPen( "square", 2 );\r
\t$.setColor( isMouseEnabled ? 2 : 4 );\r
\t$.rect( 0, 0, 300, 200 );\t\r
}\r
"""

parameters = [ ]
[[returns]]
type = "void"
description = "This function does not return a value."
