title = "stopAudioPool"
category = "sound"
isScreen = false
summary = "Stops and audio pool if it is currently playing audio."
description = ""
example = """
let soundPool = $.createAudioPool( "media/sound.wav", 1 );
$.ready( function () {
	$.playAudioPool( soundPool );
	setTimeout( function () {
		$.stopAudioPool( soundPool );
	}, 500 );
} );
"""

[[parameters]]
name = "audioId"
type = "any"
description = "The audio id of the audio pool."

[[returns]]
type = "void"
description = "This function does not return a value."
