title = "swapColor"
category = "colors"
isScreen = true
summary = "Swaps a color in the screens palette with a new color and updates the screen colors."
description = ""
example = """
$.screen( "300x200" );\r
$.setColor( 2 );\r
$.print( "HELLO" );\r
$.swapColor( 2, "red" );\r
"""

[[parameters]]
name = "oldColor"
type = "any"
description = "The color that needs to be swapped out."

[[parameters]]
name = "newColor"
type = "any"
description = "The new color."

[[returns]]
type = "void"
description = "This function does not return a value."
