title = "width"
category = "graphics"
isScreen = true
summary = "Gets the width of the screen."
description = ""
parameters = [ ]
example = """
$.screen( "300x200" );\r
$.print( "Width: " + $.width() );\r
"""

[[returns]]
type = "void"
description = "The width of the screen."
