methods = [
	"clearKeys",
	"ingamepads",
	"inkey",
	"findColor",
	"offgamepad",
	"offkey",
	"ongamepad",
	"onkey",
	"setActionKey",
	"setAutoRender",
	"setBlendMode",
	"setColors",
	"setDefaultInputFocus",
	"setErrorMode",
	"setFontSize",
	"setPen",
	"startKeyboard",
	"stopKeyboard",
	"swapColor",
	"render"
]