methods = [
	"cancelInput",
	"clearKeys",
	"createAudioPool",
	"deleteAudioPool",
	"ingamepads",
	"inkey",
	"inmouse",
	"inpress",
	"input",
	"intouch",
	"findColor",
	"offclick",
	"offgamepad",
	"offkey",
	"offmouse",
	"offpress",
	"offtouch",
	"onclick",
	"ongamepad",
	"onkey",
	"onmouse",
	"onpress",
	"ontouch",
	"play",
	"playAudioPool",
	"point",
	"printTable",
	"setActionKey",
	"setAutoRender",
	"setBlendMode",
	"setColors",
	"setDefaultInputFocus",
	"setEnableContextMenu",
	"setErrorMode",
	"setFontSize",
	"setInputCursor",
	"setPalColor",
	"setPen",
	"setPinchZoom",
	"setPixelMode",
	"setVolume",
	"startKeyboard",
	"startMouse",
	"startTouch",
	"stopKeyboard",
	"stopMouse",
	"stopPlay",
	"stopSound",
	"stopTouch",
	"swapColor",
	"render"
]

objects = []