methods = [
	"cancelInput",
	"clearKeys",
	"createAudioPool",
	"deleteAudioPool",
	"ingamepads",
	"inkey",
	"input",
	"findColor",
	"offgamepad",
	"offkey",
	"ongamepad",
	"onkey",
	"play",
	"playAudioPool",
	"setActionKey",
	"setAutoRender",
	"setBlendMode",
	"setColors",
	"setDefaultInputFocus",
	"setErrorMode",
	"setFontSize",
	"setPen",
	"setVolume",
	"startKeyboard",
	"stopKeyboard",
	"stopPlay",
	"stopSound",
	"swapColor",
	"render"
]