methods = [
	"ingamepads",
	"findColor",
	"offgamepad",
	"ongamepad",
	"setAutoRender",
	"setBlendMode",
	"setColors",
	"setDefaultInputFocus",
	"setErrorMode",
	"setFontSize",
	"setPen",
	"swapColor",
	"render"
]