title = "getAllScreens"
category = "core"
isScreen = false
summary = "Returns an array of all screen API objects."
description = """
Gets all created screens as an array of screen API objects. Each object has screen=true and an id
property.
"""
example = """
$.screen( "320x200" );
$.screen( "320x200" );
const screens = $.getAllScreens();
$.print( `Number of screens = ${screens.length}` );
"""

[[returns]]
type = "Array<Screen>"
typeDesc = "*Array"
description = "Array of screen API objects."
