title = "getDefaultPal"
category = "colors"
isScreen = false
summary = """
Gets default palette and returns an array with all the color data. The default color palette defines what colors are\r
available when a new screen is created."""
description = ""
example = """
$.screen( "300x200" );
var pal = $.getDefaultPal();
$.setColor( 4 );
$.print( `Color 4 in default pal = [ ${pal[ 4 ].array.join( ", " )} ]` );
"""

parameters = [ ]
[[returns]]
type = "Array<PiColor>"
typeDesc = "*Array"
description = "An array of color data for the default color palette."
