title = "getImage"
category = "images"
isScreen = false
summary = "Gets the image element by name."
description = """
Returns the underlying Image or Canvas element for a previously loaded image.
"""
example = """
$.screen( "300x200" );
$.loadImage( "media/player.png", "player" );
$.ready( () => {
	const img = $.getImage( "player" );
	$.drawImage( img, 150, 100, null, 0.5, 0.5, 1, 1, 0 );
} );
"""

[[parameters]]
name = "name"
type = "string"
description = "Image name."

[[returns]]
type = "HTMLImageElement | HTMLCanvasElement"
typeDesc = "*HTMLElement"
description = "The actual Image or Canvas element."
