title = "getImage"
category = "images"
isScreen = false
summary = "Gets the image element by name."
description = """
Returns the underlying Image or Canvas element for a previously loaded image.
"""
example = """
const img = $.getImage( { "name": "player" } );
"""

[[parameters]]
name = "name"
type = "string"
description = "Image name."

[[returns]]
type = "HTMLImageElement | HTMLCanvasElement"
typeDesc = "*HTMLElement"
description = "The actual Image or Canvas element."
