title = "cancelInput"
category = "keyboard"
isScreen = true
plugin = "keyboard"
summary = "Cancels the current input prompt on this screen."
description = """
Cancels the active input prompt on the current screen. The input promise will resolve with null,
and the callback (if provided) will also be passed in the value null.
"""
example = """
$.screen( "300x200" );
$.print( "\\n" );
$.input( "What is your name? ", null );
$.onkey( "Escape", "down", function () {
	$.print( "\\nInput Canceled" );
	$.cancelInput();
}, true );
"""

[[returns]]
type = "void"
description = "This function does not return a value."

