title = "startKeyboard"
category = "keyboard"
isScreen = false
plugin = "keyboard"
summary = "Starts keyboard input monitoring."
description = """
Starts the keyboard input monitoring system. This initializes event listeners for keydown and
keyup events.

Note: the keyboard automatically starts when key commands are called, but this command can be
used to restart it after calling stopKeyboard.
"""
example = """
$.screen( "300x200" );
$.stopKeyboard();
$.print( "Keyboard will be enabled in 3 seconds." );
$.onkey( "any", "down", () => {
	$.print( "Key pressed!" );
} );
setTimeout( () => {
	$.print( "Keyboard is enabled" );
	$.startKeyboard();
}, 3000 );
"""

[[returns]]
type = "void"
description = "This function does not return a value."

