title = "stopMouse"
category = "pointer"
isScreen = true
plugin = "pointer"
summary = "Stops mouse input tracking for this screen."
description = """
Stops mouse event listeners on the screen canvas. Mouse tracking will no longer update until
startMouse() is called again.
"""
example = """
$.screen( "300x200" );
$.print( "Mouse will be stopped in 3 seconds." );
$.onmouse( "move", ( mouseData ) => {
	$.setPosPx( mouseData.x, mouseData.y );
	var pos = $.getPos();
	$.setPos( pos.col, pos.row );
	$.setColor( 13 );
	$.print( "+", true );
} );
setTimeout( () => {
	$.setPos( 0, 1 );
	$.setColor( 7 );
	$.print( "Mouse is stopped" );
	$.stopMouse();
}, 3000 );
"""

[[returns]]
type = "void"
description = "This function does not return a value."
