title = "stopTouch"
category = "pointer"
isScreen = true
plugin = "pointer"
summary = "Stops touch input tracking for this screen."
description = """
Stops touch event listeners on the screen canvas. Touch tracking will no longer update until
startTouch() is called again.
"""
example = """
$.screen( "300x200" );
$.print( "Touch will be stopped in 3 seconds." );
$.ontouch( "move", ( touchData ) => {
	const touch = touchData[ 0 ];
	$.setPosPx( touch.x, touch.y );
	var pos = $.getPos();
	$.setPos( pos.col, pos.row );
	$.setColor( 13 );
	$.print( "+", true );
} );
setTimeout( () => {
	$.setPos( 0, 1 );
	$.setColor( 7 );
	$.print( "Touch is stopped" );
	$.stopTouch();
}, 3000 );
"""

[[returns]]
type = "void"
description = "This function does not return a value."
