title = "setPrintSize"
category = "text"
isScreen = true
summary = "Sets the scale factor for printed text."
description = """
Sets the horizontal and vertical scale factors for bitmap font rendering. This allows you to
make text larger or smaller. Scale values must be numbers greater than 0.

Use padX and padY to add extra padding between characters when the print to the screen.
"""
example = """
$.screen( "320x200" );
$.setFont( 1 );
$.print( "Normal size" );
$.setPrintSize( 2, 2 );
$.print( "Double size" );
$.setPrintSize( { "scaleWidth": 1, "scaleHeight": 2.5 } );
$.print( "Ultra thin tall font" );
"""

[[parameters]]
name = "scaleWidth"
type = "number"
description = "Horizontal scale factor (must be number >= 0)."
optional = true

[[parameters]]
name = "scaleHeight"
type = "number"
description = "Vertical scale factor (must be number >= 0)."
optional = true

[[parameters]]
name = "padX"
type = "number"
description = "Extra horizontal padding between characters in pixels. Defaults to 0."
optional = true

[[parameters]]
name = "padY"
type = "number"
description = "Extra vertical padding between lines in pixels. Defaults to 0."
optional = true


[[returns]]
type = "void"
description = "This function does not return a value."
