title = "stopAudio"
category = "sound"
isScreen = false
plugin = "sound"
summary = "Stops audio from an audio pool or all audio pools."
description = """
Stops all playing instances in the specified audio pool, or stops all audio pools if audioId is null.
"""
example = """
$.screen( "300x200" );
let audio = $.loadAudio( "media/sound.wav", null, 1 );
$.ready( function () {
	$.print( "Press any key to hear sound" );
	$.onkey( "any", "down", () => {
		$.playAudio( audio );
		setTimeout( function () {
			$.stopAudio( audio );
		}, 500 );
	} );
} );
"""

[[parameters]]
name = "audioId"
type = "string"
description = "Audio pool ID. If null, stops all audio pools."
optional = true

[[returns]]
type = "void"
description = "This function does not return a value."
